### ISSUE TITLE
About the Artist

### ISSUE THREAD

**Issue by Moni73** [Moni73/KunstStuebchen-Capstone#1]
## Value statement - a requirement, not a solution
Here the artist briefly introduces himself to the user.
...and the user receives a short overview 
of the Materials the Artist prefers to work with. 

## Description (Text, Scribble, Wireframe, Design)
<img width="201" alt="Bildschirmfoto 2022-05-02 um 11 44 05" src="https://user-images.githubusercontent.com/100587808/166215461-2d4372a0-2f73-4842-bf08-24aa9a58da0a.png">

## Acceptance criteria
- [ ] User sees what the Artist looks like
- [ ] Information about the Artist
- [ ] Information about the Materials used

## Tasks
- [ ] Design header with logo only
- [ ] Design footer 
- [ ] Photo of the Artist
- [ ] Text : Who is the Artist
- [ ] Text : What materials does he work with

## Size
(medium)

**Comment by mpagels** [comment]
Do you need the `Footer` component? It is not clear what the purpose is.

Besides that, it looks clear. Have fun coding!

**Comment by Moni73** [comment]
Only Design - Thanks!
