### ISSUE TITLE
Exhibition dates

### ISSUE THREAD

**Issue by Moni73** [Moni73/KunstStuebchen-Capstone#2]
## Value statement - a requirement, not a solution
Here the user receives information
about the most important art exhibition dates
from the one artist

## Description (Text, Scribble, Wireframe, Design)
<img width="226" alt="Bildschirmfoto 2022-05-04 um 12 30 56" src="https://user-images.githubusercontent.com/100587808/166665175-5fbd9f11-5237-4da4-aa03-d30e5a4699f2.png">

## Acceptance criteria
- [ ] User receives an overview of art exhibitions
- [ ] Dates
- [ ] Location

## Tasks
- [ ] Use of bootstrap
- [ ] For the information bar i use a timeline block - left / right with time points
- [ ] Insert the data ( place, event, date) as text (first time)

## Size
(small)

**Comment by julialoeschel** [comment]
Hi Monique. 
Usually the Value statements follow specific rules. 

**As a** ...(user, Author, logged in User...)
**I need** ...(describe the goal)
**to be able to** ...(describe the reason)

also I guess this will be a second page, so you implement react router? this information might go to  **Tasks**.
also in this case, there is no Button that leads back to the first page. ( and also no button that leads to here ;) )

In **Tasks** we do not mention things like Imports. The right Tasks to mention here will be "implement router" , "crate components", "testing" if you have that, "storybook" and simmilar things. If you get Data fom somewhere, this also would be the rigth place to mention that. 
By the way, where does the data come from? If you write a data File, mention this as well :) 


in **Acceptance criteria** you write criteria that need to be fullfilled to pass the userstory. Please write out what is the criteria here (short sentance is fine, but make it understandable). Criterias shall be like "A list of events is displayed" , " an event shall contain date and time and location" .... 

hope that helps.
